In [1]:
import qiskit.quantum_info
from qiskit import *
import qiskit

from SYMQCircuit import *

In [14]:
nr = 1
size = 2

test = QuantumCircuit(size)
test.cnot(control_qubit=1,target_qubit=0)
test.draw()
#a = test2.get_circuit_unitary()
#print(np.allclose(a,b))


┌───┐
q_0: ┤ X ├
     └─┬─┘
q_1: ──■──

In [15]:
b = qiskit.quantum_info.Operator(test).data
print(b.real)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


# Testing 1 qubit gates:

In [2]:


test = QuantumCircuit(size)
test.x(nr)
b = qiskit.quantum_info.Operator(test).data

test2 = SYMQCircuit(size)
test2.add_x(nr)
a = test2.get_circuit_unitary()
print(np.allclose(a,b))

True


In [3]:
test = QuantumCircuit(size)
test.y(nr)
b = qiskit.quantum_info.Operator(test).data

test2 = SYMQCircuit(size)
test2.add_y(nr)
a = test2.get_circuit_unitary()
print(np.allclose(a,b))

True


In [4]:
test = QuantumCircuit(size)
test.z(nr)
b = qiskit.quantum_info.Operator(test).data

test2 = SYMQCircuit(size)
test2.add_z(nr)
a = test2.get_circuit_unitary()
print(np.allclose(a,b))

True


In [5]:
test = QuantumCircuit(size)
test.h(nr)
b = qiskit.quantum_info.Operator(test).data

test2 = SYMQCircuit(size)
test2.add_h(nr)
a = test2.get_circuit_unitary()
print(np.allclose(a,b))

True


In [6]:
test = QuantumCircuit(size)
test.rx(1/3,nr)
b = qiskit.quantum_info.Operator(test).data

test2 = SYMQCircuit(size)
test2.add_rx(nr,1/3)
a = test2.get_circuit_unitary()
print(np.allclose(a,b))

True


In [7]:
test = QuantumCircuit(size)
test.ry(1/3,nr)
b = qiskit.quantum_info.Operator(test).data

test2 = SYMQCircuit(size)
test2.add_ry(nr,1/3)
a = test2.get_circuit_unitary()
print(np.allclose(a,b))

True


In [8]:
test = QuantumCircuit(size)
test.rz(1/3,nr)
b = qiskit.quantum_info.Operator(test).data

test2 = SYMQCircuit(size)
test2.add_rz(nr,1/3)
a = test2.get_circuit_unitary()
print(np.allclose(a,b))

True


In [9]:
test = QuantumCircuit(size)
test.rz(1/3,nr)
test.ry(2/3,nr)
test.ry(4/3,nr)
test.x(nr)
test.h(nr)
test.rx(2/7,nr)
b = qiskit.quantum_info.Operator(test).data

test2 = SYMQCircuit(size)
test2.add_rz(nr,1/3)
test2.add_ry(nr,2/3)
test2.add_ry(nr,4/3)
test2.add_x(nr)
test2.add_h(nr)
test2.add_rx(nr,2/7)
a = test2.get_circuit_unitary()
print(np.allclose(a,b))

True
